[104] Replaces regular hamburger menu behavior with a branded version
material-components/material-components-flutter-codelabs pull request #22
Opened 2018-05-16 19:36 UTC by clocksmith

- Adds slanted menu icon assets
- Adds slanted menu hamburger and diamond as main menu icon
- Removes text title from back/open view

2018-05-16 20:11 UTC, willlarche commented
Yay! Please add screenshots.

2018-05-16 22:24 UTC, clocksmith commented
![simulator screen shot - iphone 7 plus - 2018-05-16 at 18 23 31](https://user-images.githubusercontent.com/591699/40147135-698c28a4-5936-11e8-97fc-bc4742f6ae9f.png)
![simulator screen shot - iphone 7 plus - 2018-05-16 at 18 24 18](https://user-images.githubusercontent.com/591699/40147136-69a940e2-5936-11e8-9c58-e2cb8fb55dbd.png)

2018-05-16 22:29 UTC, clocksmith commented
Please let me merge this so I can simultaneously make the documentation changes.

2018-05-16 23:36 UTC, clocksmith commented
Rebased off new changes, no conflicts, ready for review again @HansMuller

2018-05-17 14:55 UTC, willlarche commented
Hans is away. So, we need as many reviews as possible.

2018-05-17 16:59 UTC, maryx commented on mdc_100_series/lib/backdrop.dart
> +          children:<Widget>[
nit: space after the :

2018-05-17 17:01 UTC, maryx commented on mdc_100_series/lib/backdrop.dart
> +            SizedBox(
We could make this a var, like `brandedIcon` and pass it as a child of the frontTitle's Row instead of having the full widget nested in. One of the comments from code lab participants was that all the code was nested/within one widget, making it hard to read for a new developer.

2018-05-17 18:53 UTC, clocksmith commented on mdc_100_series/lib/backdrop.dart
> +          children:<Widget>[
done

2018-05-17 18:53 UTC, clocksmith commented on mdc_100_series/lib/backdrop.dart
> +            SizedBox(
done

2018-05-17 18:53 UTC, clocksmith commented
PTAL

2018-05-17 21:08 UTC, willlarche requested changes

2018-05-17 21:08 UTC, willlarche commented on mdc_100_series/lib/backdrop.dart
> +    var brandedIcon = Row(children: <Widget>[
Since this is educational code. Move this down to the `icon` field instead of in a variable.

2018-05-17 21:08 UTC, willlarche commented on mdc_100_series/lib/backdrop.dart
> +      ImageIcon(AssetImage('assets/slanted_menu.png')),
Do you need to paint them brown?

2018-05-18 14:50 UTC, willlarche commented on mdc_100_series/lib/backdrop.dart
> +    var brandedIcon = Row(children: <Widget>[
Actually, @maryx had info I didn't. Ignore this request.

2018-05-18 14:56 UTC, clocksmith commented on mdc_100_series/lib/backdrop.dart
> +    var brandedIcon = Row(children: <Widget>[
Ack

2018-05-18 14:57 UTC, clocksmith commented on mdc_100_series/lib/backdrop.dart
> +      ImageIcon(AssetImage('assets/slanted_menu.png')),
Sounds like a great opportunity to talk about Icon Themes, will do in future PR

2018-05-18 14:57 UTC, clocksmith commented
Resolved

2018-05-18 14:58 UTC, willlarche approved these changes

2018-05-18 19:17 UTC, clocksmith commented
Can I go ahead and merge?

2018-05-18 19:49 UTC, merged