Add branded icon menu nav animation
material-components/material-components-flutter-codelabs pull request #28
Opened 2018-05-24 17:29 UTC by clocksmith

mock: https://material.io/design/assets/1o4ts_Rfz0X97TaapdQ-9YON6O3WzE3WZ/casestudies-shrine-backdrop-1b.mp4

screen recording: not allowed in this PR, but I will email it to reviewers shortly.

Notes:
1. The icons are incorrectly defaulted to 24dp, but they should be 18dp.
2. The fling velocity may be backwards in the toggle animations, so start and end for these animations might technically be in reverse.
3. FadeTransition vs Opacity: While browsing the docs, I quickly found FadeTransition as a recommendation to use for this animation, but I also see Opacity is already being used in a similar manner.
4. I would like to learn how to properly squash local commits into more concise messages for github history.
5. I would like to propose that the entire .idea folder (and other project files) be listed in the .gitignore. If a goal of the codelab is to make it so that there is minimal setup locally, then including .idea files that are specific to one's local machine may do more harm than good, especially if the person taking this codelab making commits to their own git project

2018-05-24 18:11 UTC, willlarche commented
5. Regarding the `.idea` files, I think I agree with you. One of the ramp up tasks for the interns is resolving the unsatisfactory setup experience which is exactly that.

2018-05-25 14:00 UTC, willlarche requested changes
So good! Thank you!!

2018-05-25 15:51 UTC, maryx approved these changes
Seems fine to me

2018-05-25 15:51 UTC, maryx commented on mdc_100_series/lib/backdrop.dart
> +    if (this.customIcon != null) {
You can also use the meta package's @required. Although this will not check for null.

2018-05-25 16:37 UTC, HansMuller approved these changes
LGTM

2018-05-25 16:37 UTC, HansMuller commented on mdc_100_series/lib/backdrop.dart
> +        begin: Offset(0.0, 0.0),
Offset.zero (here and elsewhere)

2018-05-29 14:49 UTC, clocksmith commented on mdc_100_series/lib/backdrop.dart
> +    if (this.frontTitle != null && this.backTitle != null) {
Good idea. require + assert non null is good here since a BackdropTitle really must have titles.

2018-05-29 14:51 UTC, clocksmith commented on mdc_100_series/lib/backdrop.dart
> +        begin: Offset(0.0, 0.0),
Done

2018-05-29 14:58 UTC, clocksmith commented on mdc_100_series/lib/backdrop.dart
> +    Animation<double> fade = new Tween<double>(
Forgot another related possible style issue regarding the ordering of the classes:

The private FrontLayer and BackdropTitle classes are listed before the actual Backdrop widget and BackdropState. Is this common practice in flutter? IMO it is easier to absorb the file as a whole if the "helper" classes are at the bottom of the file.

2018-05-29 15:04 UTC, HansMuller commented on mdc_100_series/lib/backdrop.dart
> +    Animation<double> fade = new Tween<double>(
That's a habit of mine (not necessarily a good one). I think best practice is to try and put the public classes first.

2018-05-29 15:17 UTC, willlarche commented on mdc_100_series/lib/backdrop.dart
> +    if (this.customIcon != null) {
I would go for building it with this custom widget. It's a tiny amount less work.

2018-05-29 16:01 UTC, willlarche approved these changes
Great job!

2018-05-29 17:03 UTC, maryx commented on mdc_100_series/lib/backdrop.dart
> +    Animation<double> fade = new Tween<double>(
I like using the temporary variables because it's easier to read (agree with feedback from from I/O), but I think overall it comes down to personal preference/whatever Flutter's style guide is. So I defer to Hans :)

2018-05-29 17:06 UTC, willlarche commented on mdc_100_series/lib/backdrop.dart
> +    Animation<double> fade = new Tween<double>(
@maryx , please contact Developer Relations and let them know your experience. If they and the technical writers agree, then it should be pushed thru all the codelabs! For now, we'll leave it inline so it doesn't stick out.

2018-05-29 17:12 UTC, willlarche commented on mdc_100_series/lib/backdrop.dart
> +    Animation<double> fade = new Tween<double>(
Thank you!

2018-05-29 19:18 UTC, clocksmith commented
Re-arranged the structure here per the comments. PTAL.

2018-05-29 20:18 UTC, HansMuller reviewed
Using FractionalTranslation is just right.

2018-05-29 20:18 UTC, HansMuller commented on mdc_100_series/lib/backdrop.dart
> +                ).animate(animation).value,
.animate(animation).value => .evaluate(animation)

Using .animate here would work but you don't need to create a new animation that's listening to `animation`

2018-05-29 20:18 UTC, HansMuller commented on mdc_100_series/lib/backdrop.dart
> +                ).animate(animation).value,
Same comment as before (and again below)

2018-05-29 20:38 UTC, clocksmith commented
Comments addressed

2018-05-29 21:58 UTC, willlarche commented on mdc_100_series/lib/backdrop.dart
> +                ).animate(animation).value,
Should we change this in the backdrop layer animation too?

2018-05-30 20:21 UTC, merged