[104] Todos for 104
material-components/material-components-flutter-codelabs pull request #51
Opened 2018-06-25 21:25 UTC by michdud

2018-06-25 21:39 UTC, willlarche requested changes
Thank you!

2018-06-25 21:39 UTC, willlarche commented on mdc_100_series/lib/supplemental/product_columns.dart
> +      //TODO: Replace Column with a ListView (104)
Space after slash

2018-06-25 21:39 UTC, willlarche commented on mdc_100_series/lib/app.dart
> +      // TODO: Implement home with a Backdrop (104)
This one could be clearer.

2018-06-25 21:39 UTC, willlarche commented on mdc_100_series/lib/app.dart
> +      // TODO: Change backLayer field to CategoryMenuPage (104)
add 'value' after 'field'

2018-06-26 14:43 UTC, michdud commented on mdc_100_series/lib/app.dart
> +      // TODO: Implement home with a Backdrop (104)
Done!

2018-06-26 14:43 UTC, michdud commented on mdc_100_series/lib/app.dart
> +      // TODO: Change backLayer field to CategoryMenuPage (104)
Done!

2018-06-26 14:44 UTC, michdud commented on mdc_100_series/lib/supplemental/product_columns.dart
> +      //TODO: Replace Column with a ListView (104)
Done!

2018-06-26 14:44 UTC, michdud commented
PTAL!

2018-06-26 15:36 UTC, willlarche approved these changes
Thank you!

2018-06-26 15:36 UTC, merged