[104] Included lines to ignore .iml files and files in idea/
material-components/material-components-flutter-codelabs pull request #67
Opened 2018-07-02 21:10 UTC by michdud

2018-07-02 22:02 UTC, willlarche commented
Great. Don't forget to delete the ones that are in the repo already.

2018-07-02 22:02 UTC, willlarche approved these changes

2018-07-02 22:58 UTC, willlarche requested changes
Let's expand it to match this PR's gitignore: https://github.com/flutter/samples/pull/3/files

2018-07-03 14:27 UTC, willlarche requested changes

2018-07-03 14:55 UTC, michdud commented on mdc_100_series/.gitignore
> +*.iml
Done!

2018-07-03 15:35 UTC, willlarche approved these changes

2018-07-03 15:36 UTC, merged